### ISSUE TITLE
BPM Display

### ISSUE THREAD

**Issue by fayescarlet64** [Curilang/DDR-A20#1]
I asked another Stepmania YouTuber (yuisin[MusicGame]) how they edited their A20 theme to display BPM instead of profile name. They told me this:

> It is a bit difficult to explain my modification... I modified "ScreenGameplay decorations" to show BPM, instead of Calorie meter. I borrowed BPMDisplay.lua from default theme and called the lua in the "ScreenGameplay decorations/default.lua"

I looked through these files, SOME things seemed to make sense, but beyond that I couldn't quite make heads or tails of this.

I'm hoping sharing this here can be helpful in some way. Thanks for reading.

**Comment by Curilang** [comment]
IT IS REALLY HELPFUL! Thank you so much to you and Yuisin!! :D

**Comment by fayescarlet64** [comment]
Oh, awesome. :D Glad to have helped just a little, even if it was just passing a message. I'll keep looking into this, too, see if we can't get a nice BPM display for the theme.

**Comment by Curilang** [comment]
It's done! Finally I did it. Wait for the update 😁
