### ISSUE TITLE
Stepmania 5 crashing on select profile screen

### ISSUE THREAD

**Issue by Loveafterglow** [Curilang/DDR-A20#5]
It starts and you play start to the profile screen and crashes, this is the log, I just downloaded this today, so i guess its a new issue, hope you can fix it. It's an amazing work you're doing <3

00:10.253: PushScreen: "ScreenSelectLanguage"
00:10.255: glTexImage2D (format GL_RGBA8, 256x32, format GL_RGBA, type GL_UNSIGNED_BYTE, pixfmt 0, imgpixfmt 0)
00:10.255: glTexImage2D (format GL_RGBA8, 512x32, format GL_RGBA, type GL_UNSIGNED_BYTE, pixfmt 0, imgpixfmt 0)
/////////////////////////////////////////
00:10.255: WARNING: Lua runtime error: GetMenuMusicPath: no menu music defined for selection
00:10.255: WARNING: [C]: error()
00:10.255: WARNING: /Themes/DDR A20/Scripts/MenuMusic.lua:32: unknown(type = profile,relative = (null),possibles = (null),selection = )
00:10.255: WARNING: (tail call): tail((*temporary) = (null))
/////////////////////////////////////////

**Comment by Curilang** [comment]
Hey! It's too easy to fix, just change the folder name of the theme to DDR A20, it's one of the instructions. 😅

**Comment by Loveafterglow** [comment]
Hey! thanks for the past reply, but I did follow all of the instructions :c I even can play the DDR A theme edit you made perfectly with the dancers and dance stages. Maybe it's not picking up the folders name? 
![imagen_2021-11-18_182314](https://user-images.githubusercontent.com/94648668/142498854-904aefee-6ad1-4a84-b91c-ceb9865c25ac.png)

**Comment by Loveafterglow** [comment]
I deleted the folder and re-installed the theme and it says this. 

00:28.058: [FileUtils] Error reading Save/UserPrefs/DDR A20/OptionRowVersion.cfg: No such file or directory

**Comment by Curilang** [comment]
Ok... so try this:
1) Press the key "Windows" and R. and search AppData.
2) Open the "Roaming" folder.
3) Search the Stepmania 5 folder and then enter in the "Save" folder.
4) Go to UserPrefs and then DDR A20 folder.
5) Erase all the files inside that folder and open Stepmania.
If you can't find that folder, use this "link", changing the part "YOUR USER" for your computer user:
C:\Users\"YOUR USER"\AppData\Roaming\StepMania 5\Save\UserPrefs\DDR A20

**Comment by Loveafterglow** [comment]
Ok! Just did that, both ways but the folder doesn't exist
![imagen_2021-11-18_184426](https://user-images.githubusercontent.com/94648668/142501710-737ac637-b303-4f86-97fa-5909e51cd532.png)

**Comment by Curilang** [comment]
Veo que hablas español, jaja
Descarga este archivo y cópialo en ese folder:
https://drive.google.com/file/d/13vOO0ySbF_zeM0hSXNY7EsTQV3J68hHu/view?usp=sharing

Este archivo trae los archivos .cfg que te pide el log.

**Comment by Loveafterglow** [comment]
Jajajaja pues si, funcionó de maravilla. no se porque mi stepmania no creo la carpeta por si misma, pero con los .cfg corrió perfectamente. Este es el mejor tema y los bailarines renderizados le dan todo ese sentimiento de estar jugando verdaderamente al arcade. muchas gracias por darte el tiempo de ayudarme

**Comment by Curilang** [comment]
Algo así me pasó cuando tuve que borrsr Stepmania de mi PC, creo que tenías que ir primero a Game Options y ahí se "crean por si solos", pero qué bueno que te sirvió. 🙌🏼
